### ISSUE TITLE
version control naming conflict

### ISSUE THREAD

**Issue by CaddyDz** [Uxie-Framework/Uxie#59]
When creating a new branch from the default [v0.9beta](https://github.com/Uxie-Framework/Uxie/tree/v0.9beta) git encounters a fatal error because of the ambiguity between the branch and the tag [v0.9beta](https://github.com/Uxie-Framework/Uxie/tree/v0.9beta).  
```
~/Uxie (v0.9beta ✓) git branch name 
warning: refname 'v0.9beta' is ambiguous.
fatal: Ambiguous object name: 'v0.9beta'.
```
There are two refs by the same name.  
Of course this can easily be worked around by checking out the actual commit hash from the head instead of the tag (using the fully qualified path) like so 
```
git checkout refs/heads/v0.9beta
git branch name
```
But this might be confusing for newcomers :octocat:  
I suggest prefixing branches by `dev-` to keep the semver intact but still distinguish tags and releases from development branches

**Comment by MohamedAmine-C** [comment]
thanks for reporting this the problem will be resolved at the release of v0.9 cause v0.9beta is intended to be a quick release for development and testing.
