### ISSUE TITLE
What is the coding style standard?

### ISSUE THREAD

**Issue by CaddyDz** [Uxie-Framework/Uxie#62]
I suggest following the PSR-2 for file formatting

**Comment by MohamedAmine-C** [comment]
@CaddyDz 
Uxie is already follow PSR-2 
can you tag files which don't follow PSR-2 ??

**Comment by CaddyDz** [comment]
Running `php-cs-fixer` shows violations of `PSR-2` almost everywhere   
I'll be making PRS for that tho
